# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install prometheus prometheus-community/prometheus -n your-namespace -f values.yaml
# helm install prometheus prometheus-community/prometheus -n rabbitmq-dev -f values.yaml
# helm install prometheus prometheus-community/prometheus -n default -f values.yaml

# values.yaml
server:
  persistentVolume:
    enabled: false
alertmanager:
  persistentVolume:
    enabled: false
rbac:
  create: true
extraScrapeConfigs: |
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-operator:15692'] # Change this to the RabbitMQ management API endpoint
