apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: rabbitmq

resources:
- configMap.yaml
- secret.yaml
- deployment.yaml
- deployment_rbac.yaml
- service.yaml
- pdb.yaml
