# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm install grafana grafana/grafana -n your-namespace -f values.yaml
# helm install grafana grafana/grafana -n rabbitmq-dev -f values.yaml

# values.yaml
adminUser: admin
adminPassword: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.rabbitmq-dev.svc.cluster.local
        isDefault: true
      # - name: RabbitMQ
      #   type: prometheus
      #   access: proxy
      #   url: http://rabbitmq.rabbitmq-dev.svc.cluster.local:15692
      #   isDefault: true

